Add generics

diff --git a/bin/ci/shellcheck b/bin/ci/shellcheck
--- a/bin/ci/shellcheck
+++ b/bin/ci/shellcheck
@@ -3,43 +3,30 @@
 set -eu
 
 readonly ROOT_DIR="$(realpath "$(dirname "$(realpath "$0")")/../..")"
-. "${ROOT_DIR}"/bin/common.inc.sh
-. "${ROOT_DIR}"/bin/dockerise.inc.bash
+source "${ROOT_DIR}"/bin/common.inc.sh
+source "${ROOT_DIR}"/bin/dockerise.inc.bash
 
-readonly binaries=(
-    bin/ci/composer-require-checker
-    bin/ci/composer-validate
-    bin/ci/docker
-    bin/ci/env
-    bin/ci/phpcs
-    bin/ci/phpdd
-    bin/ci/phpstan
-    bin/ci/phpunit
-    bin/ci/phpunit-coverage
-    bin/ci/shellcheck
-    bin/ci/unused-scanner
-    bin/ci/validate
-    bin/release/changelog
-    bin/release/code-lines
-    bin/release/docker
-    bin/release/env
-    bin/release/phpunit-coverage
-    bin/release/prepare
-    bin/common.inc.sh
-    bin/composer
-    bin/dockerise.inc.bash
-)
+filesToCheck=()
+files=$(find "${ROOT_DIR}"/bin)
+for file in ${files}; do
+    if [ -f "${file}" ] && [ "${file:(-4)}" != ".php" ]; then
+        filesToCheck+=("${file}")
+    fi
+done
 
 exitCode=0
-for binary in "${binaries[@]}"; do
+for fileToCheck in "${filesToCheck[@]}"; do
     set +e
     # SC1090: Can't follow non-constant source. Use a directive to specify location.
-    # SC1091: Not following: was not specified as input
-    # SC2034: CI_DOCKER_IMAGE_NAME appears unused. Verify use (or export if used externally).
-    # SC2086: Double quote to prevent globbing and word splitting. (needed for ${DOCKER_INTERACTIVE_PARAMETER})
-    # SC2155: Declare and assign separately to avoid masking return values.
-    # SC2181: Check exit code directly with e.g. 'if mycmd;', not indirectly with $?.
-    shellcheck --color=always --exclude SC1090,SC1091,SC2034,SC2086,SC2155,SC2181 "${binary}"
+    # SC1091 (info): Not following: ./../global-vars.inc.bash was not specified as input (see shellcheck -x).
+    # SC2034 (warning): OUTPUT_REDIRECT_PATHNAME appears unused. Verify use (or export if used externally).
+    # SC2086 (info): Double quote to prevent globbing and word splitting.
+    # SC2015 (info): Note that A && B || C is not if-then-else. C may run when A is true.
+    # SC2068 (error): Double quote array expansions to avoid re-splitting elements.
+    # SC2181 (style): Check exit code directly with e.g. 'if ! mycmd;', not indirectly with $?.
+    # SC2155 (warning): Declare and assign separately to avoid masking return values.
+    # SC2317 (info): Command appears to be unreachable. Check usage (or ignore if invoked indirectly).
+    shellcheck --color=always --exclude SC1090,SC1091,SC2034,SC2086,SC2015,SC2068,SC2181,SC2155,SC2317 "${fileToCheck}"
     if [ ${?} != 0 ]; then
         exitCode=1
     fi
@@ -47,6 +34,6 @@ for binary in "${binaries[@]}"; do
 done
 
 if [ "${exitCode}" == 0 ]; then
-    echo -e "\e[42m All files contains valid syntax. \e[0m"
+    printf "\e[42m %s files contains valid syntax. \e[0m\n" "${#filesToCheck[@]}"
 fi
 exit ${exitCode}
